### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by aaronneilwood** [tillkruss/alfred-lorem-ipsum#1]
Great work! Is it possible to randomize the text that is generated?

**Comment by tillkruss** [comment]
What exact command are you using that isn't random?

**Comment by aaronneilwood** [comment]
Thanks for the reply:

For example, ‘lorem word 1’ will always return ‘Lorem.’ ‘lorem word 3’ will always return ‘Lorem ipsum dolor.'

I’d love for a way to grab a different word/sentence/paragraph every time the command is run. Thoughts?

- Aaron

On Thu, Jan 12, 2017 at 11:15 AM "Till Krüss"

<
mailto:
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

What exact command are you using that isn't random?

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/tillkruss/alfred-lorem-ipsum/issues/1#issuecomment-272223895
, or

**Comment by tillkruss** [comment]
It's only for `words` right?

**Comment by aaronneilwood** [comment]
Words would be the most useful thing to have randomized, followed by sentences, then paragraphs. 

On Thu, Jan 12, 2017 at 11:25 AM "Till Krüss"

<
mailto:
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

It's only for

words

right?

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/tillkruss/alfred-lorem-ipsum/issues/1#issuecomment-272226307
, or

**Comment by tillkruss** [comment]
That would mean we never have "Lorem ipsum..." at the beginning and it's always randomized.

You can add `$lipsum->word(1);` before line 33 to make that happen. Let me know how that's going in a week.

**Comment by aaronneilwood** [comment]
Works perfectly! Really appreciate your time. The randomization is great for design mockups so the placeholder content looks a little more natural. Huge time saver, and the best lorem ipsum plugin I’ve seen. Nice work!

- Aaron

On Thu, Jan 12, 2017 at 11:39 AM "Till Krüss"

<
mailto:
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

That would mean we never have "Lorem ipsum..." at the beginning and it's always randomized.

You can add

$lipsum->word(1);

before line 33 to make that happen. Let me know how that's going in a week.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/tillkruss/alfred-lorem-ipsum/issues/1#issuecomment-272230043
, or

**Comment by tillkruss** [comment]
Fixed in v0.2.0.
