### ISSUE TITLE
Search Google instead of execute command

### ISSUE THREAD

**Issue by mavsar** [tillkruss/alfred-lorem-ipsum#10]
The problem is when using this workflow I get to search google instead of execute command ... this happened on my M1 ... any ideas?

<img width="691" alt="image" src="https://user-images.githubusercontent.com/17925412/153755021-9f0d7f7b-58ab-442d-b1a4-4d7c8291969c.png">

**Comment by rverrips** [comment]
This may be related to an issue with the php implementation.  

1 - Do you have php installed? In newer versions of MacOS php is no longer installed by default. (Run "php -v" and "which php" in a terminal window to confirm) 

2 - Which version of the Alfred workflow/plug-in are you running?  (Earlier versions of the workflow didn't handle the php requirement as it did not need to)

**Comment by tillkruss** [comment]
Please post your debug logs from within the Alfred Workflow.

**Comment by trijste** [comment]
I happened upon here with the same issue. I checked in the terminal and had no PHP. I ran it from `brew install PHP` and tried again after the installation finished. Works incredibly well. I hope I have the chance to use it again!
