### ISSUE TITLE
Does this no longer work?

### ISSUE THREAD

**Issue by ibrychgo** [tillkruss/alfred-lorem-ipsum#11]
This workflow APPEARS to work, but when I select sentences/paragraphs/words it then moves on to do a google search with that phrase rather than generating and copying to clipboard. 

I've removed and reinstalled. Not sure what else I should be looking for to get this working again.

Any help would be appreciated. I feel crippled without this workflow.

**Comment by tillkruss** [comment]
You system probably doesn't have PHP any more since a recent macOS upgrade.

**Comment by ibrychgo** [comment]
Ahhhh! That makes perfect sense!!!! I DID go through an update recently. I'll reinstall PHP and then the workflow. 

THANK YOU SO MUCH FOR THE FAST RESPONSE!
