### ISSUE TITLE
Name PHP as a requirement

### ISSUE THREAD

**Issue by merchako** [tillkruss/alfred-lorem-ipsum#7]
I've been struggling to get this workflow to work, and I couldn't figure out why until I saw PHP mentioned in an issue thread. Could you mention that PHP is a requirement in `Readme.md`?

**Comment by rverrips** [comment]
Hi @merchako 
Sorry to hear about your challenges.  This is indeed something which only recently occurred as PHP was included with MacOS up until the current version, 12, a.k.a. Monterey.   ([see this](https://developer.apple.com/forums/thread/681907)) 
Can you confirm you have a new / fresh version of MacOS and or did not upgrade from MacOS 11?  
(In my tests upgrading from MacOS 11 preserves the installed version of php, but I'd like to confirm that with you if I may).   
Thanks
Roy

**Comment by tillkruss** [comment]
@merchako: Good call. PHP used to be pre-installed on macOS until recently like @rverrips mentioned.

**Comment by merchako** [comment]
As far as I know, this machine was upgraded to 12 Monterey from macOS 11 Big Sur or earlier. I bought it in June 2021, so  it would have come with 11 Big Sur, and I don't think I've ever wiped it. 

If you know of a better way to figure out if this is a new/fresh version of macOS, I'm all ears, @rverrips.

**Comment by rverrips** [comment]
> As far as I know, this machine was upgraded to 12 Monterey from macOS 11 Big Sur or earlier. I bought it in June 2021, so it would have come with 11 Big Sur, and I don't think I've ever wiped it.
> 
> If you know of a better way to figure out if this is a new/fresh version of macOS, I'm all ears, @rverrips.

Thanks @merchako 

It was more for my personal understanding of how to try avoid this in future / for other users - @tillkruss's decision to simply add it as requirement simplifies things well enough. 

Thanks for your patience and help with this - Happy to hear things are working now.
